services:

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: music_recommendation_system_db
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis-broker
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - ../shared_models:/shared_models
      - hf_cache:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/root/.cache/huggingface
      - DATABASE_URL=mysql+pymysql://root:123456@db:3306/music_recommendation_system_db
      - JWT_SECRET_KEY=your-secret-key-here
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRE_MINUTES=1440
      # PhoBERT đã được tích hợp trực tiếp vào backend (không cần service riêng)
      # Model file: backend/app/ai/models/best_model.pt
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  trainer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.trainer
    volumes:
      - ../shared_models:/shared_models
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - backend
      - redis
      - db
    command: >
      sh -c "
      celery -A trainer.celery_app.celery beat --loglevel=info &
      celery -A trainer.celery_app.celery worker --loglevel=info
      "

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: vite-frontend
    ports:
      - "5173:5173"
    volumes:
      - ../Frontend/src:/app/src
    depends_on:
      - backend

volumes:
  mysql_data:
  models_volume:
  hf_cache:
