FROM node:20

WORKDIR /app

# Copy package files
COPY Frontend/package.json Frontend/package-lock.json ./

# Install dependencies
RUN npm install

# Copy frontend source code
COPY Frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
